#!/bin/bash
chown vincent:staff ./#0-current_working_directory# ./0-current_working_directory ./0-current_working_directory~ ./100-change_owner_and_group ./12-file_type ./#1-listit# ./1-listit ./2-bring_me_home ./3-listfiles ./4-listmorefiles ./5-listfilesdigitonly ./6-firstdirectory ./6-firstdirectory12-file_type ./7-movethatfile ./8-firstdelete ./README.md ./tmp
